Repository coblox/bobtimus, pull requests merged in 2019-07, with the labels that each got.

#52 Bug fix for the retry mechanism
  src/actionExecutor.ts
  tests/actionExecutor.spec.ts
Labels: automagically-mergify-this

#51 Use an enum for Assets
  src/actionSelector.ts
  src/asset.ts
  src/comitNode.ts
  src/config.ts
  src/ledger.ts
  src/rates.ts
  src/ratesConfig.ts
  tests/actionExecutor.spec.ts
  tests/actionSelector.spec.ts
  tests/config.spec.ts
  tests/configs/default.toml
  tests/configs/noSeedWords.toml
  tests/rates.spec.ts
  tests/ratesConfig.spec.ts
Labels: automagically-mergify-this

#67 Say what is going wrong in the Error
  src/wallets/ethereum.ts
Labels: automagically-mergify-this

#66 Introduce resolveOrReject analogous to returnOrThrow
  tests/doubles/bitcoinWalletStub.ts
  tests/doubles/ethereumWalletStub.ts
  tests/doubles/resolveOrReject.ts
  tests/rates/tradeEvaluationService.spec.ts
Labels: automagically-mergify-this

#65 Use `calculate` as the verb in `getAmountsToCalculate`
  src/rates/testnetMarketMaker.ts
  tests/rates/testnetMarketMaker.spec.ts
Labels: automagically-mergify-this

#64 Rename `getRateService` to `create...`
  src/index.ts
  src/rates/tradeEvaluationService.ts
  tests/rates/tradeEvaluationService.spec.ts
Labels: automagically-mergify-this

#62 Use `reduce` instead of mutable variable
  src/wallets/bitcoin.ts
Labels: automagically-mergify-this

#68 Include error objects in log statements
  src/bitcoin/bitcoinFeeService.ts
  src/ethereum/ethereumGasPriceService.ts
  src/index.ts
  src/rates/tradeEvaluationService.ts
Labels: automagically-mergify-this

#63 Favor destructing objects to avoid local variables
  tests/actionSelector.spec.ts
Labels: automagically-mergify-this

#61 Remove console.log spam from test execution
  tests/rates/tradeEvaluationService.spec.ts
Labels: automagically-mergify-this

#70 Add test with unsupported erc20 token
  tests/actionSelector.spec.ts
  tests/stubs/bitcoinEther/swapsWithErc20AcceptDecline.siren.json
Labels: automagically-mergify-this

#77 Allow bobtimus to use the bitcoind .cookie file for authentication
  README.md
  src/bitcoin/bitcoinCoreRpc.ts
  src/bitcoin/bitcoindAuthCookie.ts
  src/config.ts
  src/index.ts
  tests/actionExecutor.spec.ts
  tests/actionSelector.spec.ts
  tests/bitcoin/bitcoindAuthCookie.spec.ts
  tests/config.spec.ts
  tests/configs/noSeedWords.toml
  tests/configs/staticRates.toml
  tests/configs/testnetMarketMaker.toml
  tests/rates/tradeEvaluationService.spec.ts
Labels: automagically-mergify-this

#76 trades-to-publish API
  package.json
  src/actionSelector.ts
  src/comitNode.ts
  src/config.ts
  src/index.ts
  src/ledger.ts
  src/ledgerExecutor.ts
  src/rates.ts
  src/rates/staticRates.ts
  src/rates/testnetMarketMaker.ts
  src/rates/tradeService.ts
  src/routes/tradesToPublish.ts
  src/wallets/ethereum.ts
  tests/actionExecutor.spec.ts
  tests/actionSelector.spec.ts
  tests/comitNode.spec.ts
  tests/config.spec.ts
  tests/configs/noSeedWords.toml
  tests/configs/staticRates.toml
  tests/configs/testnetMarketMaker.toml
  tests/doubles/ethereumWalletStub.ts
  tests/rates/staticRates.spec.ts
  tests/rates/testnetMarketMaker.spec.ts
  tests/rates/tradeService.spec.ts
  tests/routes/tradesToPublish.spec.ts
  yarn.lock
Labels: automagically-mergify-this

#81 Add testnet support for Ethereum to LedgerExecutor
  src/ledgerExecutor.ts
  tests/ledgerExecutor.spec.ts
  yarn.lock
Labels: added-mid-sprint

#83 Fix timeout crash
  src/bitcoin/bitcoinCoreRpc.ts
  src/index.ts
  tests/wallets/ethereum.spec.ts
Labels: added-mid-sprint, automagically-mergify-this, 🐛 bug

#89 Refactor - Clean up Config deps
  src/actionExecutor.ts
  src/actionSelector.ts
  src/comitNode.ts
  src/config.ts
  src/index.ts
  src/rates/tradeService.ts
  tests/actionExecutor.spec.ts
  tests/actionSelector.spec.ts
  tests/comitNode.spec.ts
  tests/config.spec.ts
  tests/rates/tradeService.spec.ts
  tests/routes/tradesToPublish.spec.ts
Labels: added-mid-sprint
