Repository coblox/bobtimus, pull requests merged in 2019-08, with the labels that each got.

#92 ERC20 support for getBalance of Ethereum Wallet
  src/asset.ts
  src/ethereum/Erc20ABI.json
  src/rates/tradeService.ts
  src/wallets/ethereum.ts
  tests/doubles/ethereumWalletStub.ts
  tests/wallets/ethereum.spec.ts
Labels: automagically-mergify-this

#98 ERC20 - ActionSelector
  src/actionSelector.ts
  src/asset.ts
  src/index.ts
  src/tokens.ts
  tests/actionSelector.spec.ts
  tests/asset.spec.ts
  tests/stubs/bitcoinEther/swapsWithDogecoinAcceptDecline.siren.json
  tests/tokens.spec.ts
Labels: automagically-mergify-this

#97 Static Rates with ERC20 tokens
  tests/rates/staticRates.spec.ts
Labels: automagically-mergify-this

#90 Remove bitcoinjs-lib deprecation warning
  src/wallets/bitcoin.ts
Labels: added-mid-sprint, automagically-mergify-this

#99 Use winston logger and log to Stackdriver Logging
  logconfig.json
  package.json
  src/actionExecutor.ts
  src/actionSelector.ts
  src/asset.ts
  src/bitcoin/bitcoinCoreRpc.ts
  src/bitcoin/bitcoinFeeService.ts
  src/bitcoin/blockchain.ts
  src/comitNode.ts
  src/config.ts
  src/ethereum/ethereumGasPriceService.ts
  src/fieldDataSource.ts
  src/index.ts
  src/ledger.ts
  src/ledgerExecutor.ts
  src/logging/logger.ts
  src/rates/staticRates.ts
  src/rates/testnetMarketMaker.ts
  src/rates/tradeService.ts
  src/routes/tradesToPublish.ts
  src/tokens.ts
  src/wallets/bitcoin.ts
  src/wallets/ethereum.ts
  tests/actionSelector.spec.ts
  yarn.lock
Labels: automagically-mergify-this

#93 Trades to offers - More functional
  src/actionExecutor.ts
  src/actionSelector.ts
  src/asset.ts
  src/bitcoin/bitcoinCoreRpc.ts
  src/fieldDataSource.ts
  src/index.ts
  src/ledgerExecutor.ts
  src/rates/balances.ts
  src/rates/staticRates.ts
  src/rates/testnetMarketMaker.ts
  src/rates/tradeService.ts
  src/routes/offersToPublish.ts
  src/sleep.ts
  src/wallets/bitcoin.ts
  src/wallets/ethereum.ts
  tests/actionExecutor.spec.ts
  tests/actionSelector.spec.ts
  tests/asset.spec.ts
  tests/doubles/bitcoinWalletStub.ts
  tests/doubles/dummyBitcoinWallet.ts
  tests/doubles/dummyDatastore.ts
  tests/doubles/dummyLedgerExecutor.ts
  tests/doubles/ethereumWalletStub.ts
  tests/doubles/mockBitcoinBlockchain.ts
  tests/ledgerExecutor.spec.ts
  tests/rates/staticRates.spec.ts
  tests/rates/testnetMarketMaker.spec.ts
  tests/routes/tradesToPublish.spec.ts
  tests/stubs/bitcoinEther/swapsWithRefund.siren.json
  tests/stubs/ethereumTransactionReceipt.json
  tests/stubs/refundBitcoin.json
  tests/stubs/refundEther.json
  tests/stubs/transactionReceipt.json
  tests/wallets/bitcoin.spec.ts
  tests/wallets/ethereum.spec.ts
Labels: added-mid-sprint

#102 print simple in console
  src/logging/logger.ts
Labels: added-mid-sprint, automagically-mergify-this

#100 Erc20 - testnet market maker
  src/asset.ts
  src/index.ts
  src/rates/balances.ts
  src/rates/testnetMarketMaker.ts
  src/rates/tradeService.ts
  src/tokens.ts
  tests/rates/balances.spec.ts
  tests/rates/testnetMarketMaker.spec.ts
  tests/rates/tradeService.spec.ts
  tests/routes/tradesToPublish.spec.ts
  tests/tokens.spec.ts
Labels: automagically-mergify-this

#107 Add prettier to dev dependencies
  package.json
  yarn.lock
Labels: added-mid-sprint

#106 Update REST API to include ERC-20 Contract Details
  src/asset.ts
  src/routes/offersToPublish.ts
  src/tokens.ts
  src/wallets/ethereum.ts
  tests/actionSelector.spec.ts
  tests/asset.spec.ts
  tests/rates/staticRates.spec.ts
  tests/rates/testnetMarketMaker.spec.ts
  tests/routes/tradesToPublish.spec.ts
  tests/tokens.spec.ts
  tests/wallets/ethereum.spec.ts
Labels: automagically-mergify-this

#111 Loglevel fix
  src/actionExecutor.ts
  src/actionSelector.ts
  src/asset.ts
  src/bitcoin/bitcoinCoreRpc.ts
  src/comitNode.ts
  src/config.ts
  src/fieldDataSource.ts
  src/index.ts
  src/ledger.ts
  src/ledgerExecutor.ts
  src/logging/logger.ts
  src/rates/testnetMarketMaker.ts
  src/rates/tradeService.ts
  src/routes/offersToPublish.ts
  src/wallets/bitcoin.ts
  src/wallets/ethereum.ts
Labels: automagically-mergify-this, 🐛 bug

#112 Add Changelog
  CHANGELOG.md
Labels: automagically-mergify-this
